version: '3.3'
services:
  angular-docker:
    build: 
      context: .
      args:
        API_URL: "  backend_api: 'https://localhost:8080/'"
    ports:
      - '4200:4200'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      # - ./front/api_gateway.conf:/etc/nginx/api_gateway.conf

    