version: '3.3'
services:
  dislinkt-frontend:
    build: 
      context: .
      args:
        API_URL: "  backend_api: 'https://localhost:8080/'"
    ports:
      - '4200:4200'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf

    # restart: on-failure
    # image: darkelfff/dislinkt-frontend:latest
    # ports:
    #   - '4200:4200'
    # volumes:
    #   - ./docker/nginx.conf:/etc/nginx/nginx.conf

    